Enable running decode from spark
medicode/tensor2tensor pull request #204
Opened 2020-09-09 11:22 UTC by fathom-jakub

This pr introduces new `shard_id` flag that is used to select proper chunk of input tfprotos for purpose of parallelization.

2020-09-09 12:53 UTC, fathom-pawel commented on tensor2tensor/bin/t2t_decoder.py
> +  if FLAGS.shard_id is None:
why are we outputting xcom only if shar_id is set?

2020-09-09 15:53 UTC, fathom-jakub commented on tensor2tensor/bin/t2t_decoder.py
> +  if FLAGS.shard_id is None:
The opposite. We're outputting xcom if shard_id is not set - that means we're running in standalone mode. If we're launching in spark, shard_id is set and we don't need the XCOM output. We probably would be fine with it being outputed anyway but I thought it's better not to do it.

2020-09-09 16:02 UTC, fathom-pawel commented on tensor2tensor/bin/t2t_decoder.py
> +  if FLAGS.shard_id is None:
how does the downstream task get the intput in that case?

2020-09-09 16:03 UTC, fathom-jakub commented on tensor2tensor/bin/t2t_decoder.py
> +  if FLAGS.shard_id is None:
from the spark pipeline output. Remember that with spark the output of decode method doesn't go anywhere as it's being launched for each partition inside workers.

2020-09-09 16:06 UTC, fathom-pawel approved these changes

2020-09-10 16:50 UTC, fathom-pawel approved these changes

2020-09-10 23:26 UTC, kvudata requested changes
why can't we just reuse the existing `worker_id` FLAG?

2020-09-11 10:03 UTC, fathom-jakub commented
> why can't we just reuse the existing `worker_id` FLAG?

We're using `shard_id` flag in other places to differentiate between sharded (spark) and non-sharded mode of execution and we rely on it being None by default. If we just used worker_id in those places, we could break execution for non-spark usage of decode.

2020-09-11 13:56 UTC, fathom-jakub commented
> why can't we just reuse the existing `worker_id` FLAG?

Ok, we can do this so this PR is not necessary.

2020-09-14 14:48 UTC, closed without merging